# Generated by Django 3.2 on 2022-07-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSlot',
            fields=[
                ('doctorslot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('slot_start_time', models.TimeField()),
                ('slot_end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('doctors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorsid', to='doctorAppointment.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='doctorAppointment.patient')),
                ('doctorslot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='doctorAppointment.doctorslot')),
                ('doctor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='doctorAppointment.doctor')),
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('doctorAppointment.doctor', 'doctorAppointment.doctorslot', 'doctorAppointment.patient'),
        ),
    ]
