# Generated by Django 3.2 on 2022-07-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAppointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_speciality', models.CharField(max_length=100)),
                ('slot_date', models.DateField()),
                ('slot_start_time', models.TimeField()),
                ('slot_end_time', models.TimeField()),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorAppointment.patient'),
        ),
    ]
