# Generated by Django 3.2 on 2022-07-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAppointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorList',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='PatientList',
            new_name='Patient',
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorslot', to='doctorAppointment.doctorslot')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientdetails', to='doctorAppointment.patient')),
            ],
        ),
    ]
