# Generated by Django 3.2 on 2022-07-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAppointment', '0003_auto_20220707_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='doctor_slot',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='doctor_speciality',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='patient_location',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='patient_name',
        ),
    ]
