# Generated by Django 3.2 on 2022-07-07 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAppointment', '0004_auto_20220707_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='doctor_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctorAppointment.doctorslot'),
            preserve_default=False,
        ),
    ]
