# Generated by Django 3.2 on 2022-07-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAppointment', '0005_appointmentdetails_doctor_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='doctor_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorAppointment.doctorslot'),
        ),
    ]
