# Generated by Django 3.2 on 2022-07-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAppointment', '0008_rename_appointmentdetails_appointmentdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentDetail',
        ),
    ]
