# Generated by Django 3.2 on 2022-07-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAppointment', '0009_delete_appointmentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('slot_start_time', models.TimeField()),
                ('slot_end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorAppointment.doctor')),
                ('doctor_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorAppointment.doctorslot')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorAppointment.patient')),
            ],
        ),
    ]
