# Generated by Django 3.2 on 2022-07-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAppointment', '0010_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='doctorslot',
            old_name='doctors_id',
            new_name='doctor_id',
        ),
    ]
