# Generated by Django 3.2 on 2022-07-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAppointment', '0011_auto_20220712_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_slot',
            new_name='doctorslot_id',
        ),
    ]
